### ISSUE TITLE
Response schemas have query parameter as properties

### ISSUE THREAD

**Issue by ilkkarinne** [fmidev/smartmet-sofp-backend#12]
The following properties should not be included in the response features as they are not included in the OMSF Observation feature types:
* place
* latlon
* lonlat

It's ok to still have these as query parameters.

**Comment by trabantdriver** [comment]
They are not included by the backend. Sampo ?

**Comment by trabantdriver** [comment]
I think this is not (purely) a backend issue, collection must have those properties set in order to be used as query parameters. Sampo ?

**Comment by ilkkarinne** [comment]
Ok, I was not aware of the core limitation on collection specific query parameters (=must match property names). @sampov2 is working on a change in this in the core

**Comment by sampov2** [comment]
I've released version 0.4.0 of the core (sofp-lib version 0.3.2) where each collection can set up additional query parameters (https://github.com/vaisala-oss/sofp-lib/blob/master/src/collection.ts#L34). When these parameters are in the data query string, core produces an AdditionalParameterFilters for the backend (https://github.com/vaisala-oss/sofp-core/blob/master/src/server/filters/additional_parameter_filter.ts). This design separates collection properties that need to have a one-to-one equivalency with query string parameters and the data model and these cases where we want a query string that is used by the API but is not necessarily connected to the data model.

Please note that the default implementation for the AdditionalParameterFilter is to throw an exception - the server cannot know what to do with them. This mandates the backend to take care of the filter and not pass it back to the core.

**Comment by trabantdriver** [comment]
backend now uses AdditionalParameterFilters
