### ISSUE TITLE
Too much data with &place=xx

### ISSUE THREAD

**Issue by tervo** [fmidev/smartmet-sofp-backend#4]
This query should return only Helsinki data? Now it returns 'grid-data' after Helsinki-data: http://beta.fmi.fi/data/3/wfs/sofp/collections/harmonie_scandinavia_surface/items?parametername=temperature,windspeedms&time=2019-01-31T10:00:00/2019-01-31T13:00:00&bbox=35,65,36,66&place=helsinki

**Comment by trabantdriver** [comment]
Location parameters are ORed together by timeseries plugin, so the result contains data within the bbox too.

**Comment by trabantdriver** [comment]
Feature, bbox should be omitted if only given place is requested
