### ISSUE TITLE
Property filters for all properties 

### ISSUE THREAD

**Issue by tervo** [fmidev/smartmet-sofp-backend#6]
All properties can not be used as filters. For example:

Specification says: 
> If features in the feature collection include a feature property that has a simple value (for example, a string or integer) that is expected to be useful for applications using the service to filter the features of the collection based on this property, you SHOULD support a parameter with the name of the feature property and with the following characteristics (using an OpenAPI Specification 3.0 fragment):
> in: query
> required: false
> style: form
> explode: false
> The schema property SHOULD be the same as the definition of the feature property in the response schema.

For example query:
http://beta.fmi.fi/data/3/wfs/sofp/collections/hirlam/items?limit=100&place=kaisaniemi&observedPropertyName=WindSpeedMS&phenomenonTime=20190225T080001
Should NOT return anything.

**Comment by trabantdriver** [comment]
Added missing properties ('observationType', 'id', 'phenomenonTime' and 'resultTime')
