### ISSUE TITLE
Times wrong in observations

### ISSUE THREAD

**Issue by tervo** [fmidev/smartmet-sofp-backend#7]
Times are in the wrong fields in observations:

For example:
http://beta.fmi.fi/data/3/wfs/sofp/collections/opendata_1m/items?time=2018-02-26T08:00:00Z/2018-02-26T09:00:00Z&place=kaisaniemi

Returns: 
```
observationType:  "MeasureObservation"
resultTime: "20180226T080000"
phenomenonTime:  "20190226T075143"
id: "BsWfsElement.1.1.9"
observedPropertyName: "Precipitation1h"
```
phenomenonTime should be 20180226T080000. I assume that resultTime _should_ be time when the observation has been available (@ilkkarinne ?). Unfortunately we do not have that information available and we need to use observation time instead.

**Comment by trabantdriver** [comment]
Fixed/swapped 'phenomenonTime' and 'resultTime' values. resultTime is set to phenomenonTime for observations.

**Comment by trabantdriver** [comment]
Fixed/swapped 'phenomenonTime' and 'resultTime' values. resultTime is set to phenomenonTime for observations.
